"""
core/prompt/templates/reasoning_synthesis.py
Shared prompt for merging multiple LLM reasoning chains into one.
Used by Diagnosis / Treatment / Prognosis post_process.
"""

REASONING_SYNTHESIS_PROMPT = """You are a medical expert specializing in clinical reasoning synthesis. You will analyze multiple reasoning chains generated by different models for the same clinical case. Your task is to integrate these diverse reasoning approaches into a comprehensive, multi-perspective clinical reasoning narrative that reflects how experienced clinicians approach complex cases. Your task may involve risk assessment, diagnosis, treatment, or prognosis analysis. Please perform the synthesis according to the specific task type.

Task instructions:
    1 analyze reasoning diversity: Review all provided reasoning chains and identify the distinct clinical perspectives, reasoning frameworks, and interpretive approaches represented. Recognize that different models may emphasize different aspects of the case (e.g., pathophysiology vs pattern recognition, organ-system focus vs syndrome-based approach, mechanistic vs probabilistic reasoning).
    2 synthesize integrated reasoning: Construct a unified clinical reasoning narrative that incorporates the strengths and insights from all distinct reasoning approaches. Your synthesis should: A) Present the clinical logic in a natural flow, as a clinician would discuss the case, B) Integrate multiple perspectives where they complement each other, C) Acknowledge alternative interpretations where reasoning chains diverge, D) Use appropriate clinical terminology and reasoning structure (e.g., 'The presentation suggests...', 'Key features include...', 'This is consistent with...', 'Alternative considerations include...').
    3 highlight reasoning dimensions: Within your integrated narrative, explicitly note when different reasoning approaches contribute unique insights, such as: A) Mechanistic reasoning (pathophysiologic mechanisms), B) Pattern recognition (clinical syndrome identification), C) Probabilistic reasoning (likelihood assessment), D) Systematic reasoning (differential diagnosis framework), E) Evidence-based reasoning (literature or guideline reference).
    4 maintain clinical authenticity: Write in the style of clinical reasoning documentation. Use phrases common in clinical discussion such as: 'Clinical presentation is most consistent with...', 'The combination of findings suggests...', 'Key diagnostic features include...', 'The temporal pattern supports...', 'Pathophysiologically, this reflects...', 'Alternative explanations to consider...'.
5. Avoid: Overly casual language, Bullet points in the main synthesis (use prose), Repetitive listing of the same findings, Non-clinical terminology
6.Structure of integrated clinical reasoning: Structure the output as a single cohesive narrative that first synthesizes a unified problem representation from all reasoning chains, then explicitly highlights areas of agreement across models (shared clinical signals), followed by key divergences in interpretation (e.g., mechanistic vs pattern-based views), and integrates these perspectives into a reconciled pathophysiologic and diagnostic understanding; next, construct a combined differential diagnosis using evidence from all chains and weigh competing options probabilistically, before converging on the most likely diagnosis with clear justification, while briefly acknowledging any residual uncertainty—overall following the flow: align → compare → integrate → evaluate → conclude. When the assigned task is not primary diagnostic reasoning (e.g., risk analysis, treatment planning, or prognosis), adapt this flow to emphasize risk stratification, therapeutic reasoning, or expected outcomes respectively while preserving the same integrative structure.
7. You should only summarize the different reasoning approaches without introducing any bias. Avoid using expressions such as "the most plausible," "most likely," or "most appropriate." Maintain an objective analytical tone. If the provided reasoning contains such exaggerated or overly confident language, your summary should exclude it.
 Important note: keep the final output under 500 words.
Output requirements:
Your final answer must be pure JSON only, using the exact structure below:
      {{"integrated_clinical_reasoning": "string"}}
Your task is to synthesize medical reasoning regarding {task_type}.

Patient information ({patient_info_note}):
{patient_context}

Here are the different reasoning chains from multiple models:
{reasoning_texts}"""


# Per pipeline key: human-readable task phrase + how the patient block aligns with model inputs.
TASK_SYNTHESIS_CONFIG = {
    "risk": {
        "synthesis_target": "risk analysis",
        "patient_info_note": "primary consultation, same information density as used for model inference",
    },
    "diagnosis_primary": {
        "synthesis_target": "diagnosis (primary visit)",
        "patient_info_note": "primary consultation, same information density as used for model inference",
    },
    "diagnosis_followup": {
        "synthesis_target": "diagnosis (follow-up visit)",
        "patient_info_note": "follow-up consultation, same information density as used for model inference",
    },
    "treatment": {
        "synthesis_target": "treatment planning",
        "patient_info_note": "treatment-plan context, same information density as used for model inference",
    },
    "prognosis": {
        "synthesis_target": "prognosis prediction",
        "patient_info_note": "prognosis-prediction context, same information density as used for model inference",
    },
}


def resolve_synthesis_fields(task_type_key: str) -> tuple[str, str]:
    """Return (synthesis_target, patient_info_note) for prompt formatting."""
    cfg = TASK_SYNTHESIS_CONFIG.get(task_type_key)
    if cfg is None:
        return (
            task_type_key,
            "context as supplied to the contributing models, aligned with inference inputs",
        )
    return (cfg["synthesis_target"], cfg["patient_info_note"])


# Backward-compatible name: map key -> short label (synthesis target only).
TASK_TYPE_MAP = {k: v["synthesis_target"] for k, v in TASK_SYNTHESIS_CONFIG.items()}
