"""Stage-organized schema package with backward-compatible re-exports."""

from .diagnosis import (
    DiagnosisFollowUpConsultationLLMOutput,
    DiagnosisLLMOutputs,
    DiagnosisLlmModelOutput,
    DiagnosisPrimaryConsultationLLMOutput,
    DiagnosisReason,
    DiagnosisRerankBundle,
    DiagnosisRerankOutput,
    DiagnosisStagePrediction,
    DiagnosisTestRecommendationModelOutput,
    DiagnosisTestScoreItem,
    FirstVisitDiagnosisOutput,
    FollowUpDiagnosisOutput,
    FollowUpInput,
    TestRecommendation,
)
from .diagnosis_config import DiagnosisConfig
from .llm_meta import LLMCallRecord, ParsedLlmJson, RawLlmTurn, RiskLlmPayload
from .pipeline import PatientCase, PipelineCase
from .prognosis import (
    ClinicalEvent,
    FunctionalStatus,
    OverallOutcome,
    PrognosisAggregateOutput,
    PrognosisInput,
    PrognosisPredictionOutput,
    PrognosisTarget,
    SymptomBurden,
    validate_prognosis_prediction_output,
)
from .risk import InsightItem, RiskInput, RiskOutput
from .shared import (
    BasicInformation,
    DiagnosisInfo,
    ExaminationItem,
    MedicalHistory,
    PhysicalExamination,
    TreatmentHistory,
)
from .treatment import (
    PerModelTreatmentOutput,
    RareTreatmentBlock,
    RareTreatmentRankedIntermediate,
    RareTreatmentRankedItem,
    TreatmentAggregateOutput,
    TreatmentGoal,
    TreatmentInput,
    TreatmentItem,
    TreatmentMatchedRecommendation,
    TreatmentPlanLlmOutput,
    TreatmentScoreItem,
    TreatmentScoreOutput,
    TreatmentScoreOverallEvaluation,
    validate_rare_treatment_output,
    validate_rare_treatment_ranked_intermediate,
    validate_treatment_plan_llm_output,
    validate_treatment_score_output,
)

__all__ = [
    "BasicInformation",
    "MedicalHistory",
    "PhysicalExamination",
    "ExaminationItem",
    "DiagnosisInfo",
    "TreatmentHistory",
    "RiskInput",
    "InsightItem",
    "RiskOutput",
    "FollowUpInput",
    "DiagnosisReason",
    "TestRecommendation",
    "FirstVisitDiagnosisOutput",
    "FollowUpDiagnosisOutput",
    "DiagnosisPrimaryConsultationLLMOutput",
    "DiagnosisFollowUpConsultationLLMOutput",
    "DiagnosisLlmModelOutput",
    "DiagnosisTestScoreItem",
    "DiagnosisTestRecommendationModelOutput",
    "DiagnosisLLMOutputs",
    "DiagnosisRerankBundle",
    "DiagnosisStagePrediction",
    "DiagnosisRerankOutput",
    "DiagnosisConfig",
    "TreatmentInput",
    "TreatmentGoal",
    "TreatmentItem",
    "TreatmentPlanLlmOutput",
    "TreatmentAggregateOutput",
    "TreatmentScoreItem",
    "TreatmentScoreOverallEvaluation",
    "TreatmentScoreOutput",
    "TreatmentMatchedRecommendation",
    "PerModelTreatmentOutput",
    "RareTreatmentRankedItem",
    "RareTreatmentBlock",
    "RareTreatmentRankedIntermediate",
    "validate_treatment_plan_llm_output",
    "validate_rare_treatment_ranked_intermediate",
    "validate_rare_treatment_output",
    "validate_treatment_score_output",
    "PrognosisInput",
    "PrognosisTarget",
    "OverallOutcome",
    "FunctionalStatus",
    "SymptomBurden",
    "ClinicalEvent",
    "PrognosisPredictionOutput",
    "PrognosisAggregateOutput",
    "validate_prognosis_prediction_output",
    "PatientCase",
    "PipelineCase",
    "RawLlmTurn",
    "ParsedLlmJson",
    "RiskLlmPayload",
    "LLMCallRecord",
]
